### ISSUE TITLE
Suggestion for new command

### ISSUE THREAD

**Issue by leeper** [openjournals/whedon-api#32]
Can I suggest a new command for whedon to handle? The final step before accepting is setting the archive. While some authors know how to do this, we don't provide a lot of detail for new users and it tends to mean editors have to type the same basic explanation repeatedly. So, can I suggest:

```
@whedon request doi
```

As a command that will trigger something like:

```
@{author} The review process is now complete. To finalize your submission and accept your paper in JOSS, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here to @{editor} with the DOI for the release.
```

**Comment by arfon** [comment]
Thanks for this suggestion @leeper. Have you looked at GitHub's [saved replies](https://blog.github.com/2016-03-29-saved-replies/) - I currently have a few set up for JOSS.

I think we _could_ add this to Whedon but I'm wondering if saved replies might be better? Thoughts?

**Comment by leeper** [comment]
Your call. I was not aware of that feature, so will definitely use it moving forward if we don't implement this.

**Comment by arfon** [comment]
Closing as stale. I think this is better handled by saved replies and the docs we have here: https://joss.readthedocs.io/en/latest/editing.html#sample-messages-for-authors-and-reviewers
