### ISSUE TITLE
Recompile recently published papers

### ISSUE THREAD

**Issue by xuanxu** [openjournals/whedon-api#68]
The papers published during the last week or so have a wrong footer, showing a reference with the year 3030 (see for example: https://doi.org/10.21105/joss.01554).

Once that issue is fixed ([PR here](https://github.com/openjournals/whedon-api/pull/67)), all the recent PDFs should be regenerated.

**Comment by arfon** [comment]
@xuanxu thanks for flagging this. I've already fixed the papers and will look into #67 shortly.
