### ISSUE TITLE
Paper compilation can fail silently

### ISSUE THREAD

**Issue by arfon** [openjournals/whedon-api#73]
This may be because the author specifies a full path to their `paper.md` so Whedon fails to clone the repository. Needs investigating.

/ cc https://github.com/openjournals/joss/issues/633

**Comment by jcolomb** [comment]
got the problem apparently. trying to compile from 
https://github.com/jcolomb/HCS_analysis/tree/joss

If I set https://github.com/jcolomb/HCS_analysis/ +  branch joss: it gives an error
if I set https://github.com/jcolomb/HCS_analysis/tree/joss , it says it compiles but link goes 404 (https://whedon.theoj.org/%7B%7D)

**Comment by jcolomb** [comment]
so I pulled requested it and it works on the master branch now.

**Comment by arfon** [comment]
Thanks for reporting this, it's a known issue that the errors should be improved.

In this case setting the repository to `https://github.com/jcolomb/HCS_analysis` and branch to `joss` worked for me:

<img width="1484" alt="Screen Shot 2019-12-11 at 9 00 58 AM" src="https://user-images.githubusercontent.com/4483/70627803-de135300-1bf4-11ea-90ef-cb1c1869b7b9.png">

**Comment by jcolomb** [comment]
Indeed, it now works ?! I assure you it did not one hour ago . (maybe it works because there is a paper.md file on the master? but it does use the joss branch.... ???)

**Comment by arfon** [comment]
> Indeed, it now works ?! I assure you it did not one hour ago . (maybe it works because there is a paper.md file on the master? but it does use the joss branch.... ???)

Not sure sorry... I'm pretty sure it's picking up files on the other branches.

**Comment by jcolomb** [comment]
yes it does. What I do not get is why it was not working one hour ago, while I made no change to that branch since then (I changed the master, though)

**Comment by arfon** [comment]
> yes it does. What I do not get is why it was not working one hour ago, while I made no change to that branch since then (I changed the master, though)

This sounds like some kind of intermittent issue. There have been some memory issues with Whedon in production recently and I'm wondering if that's what is going on here.
