### ISSUE TITLE
Multi-journal Whedon-API

### ISSUE THREAD

**Issue by arfon** [openjournals/whedon-api#8]
We'd like to be able to run a single instance of Whedon across multiple journal review issues. This means that we need to do a few things:

- [x] Extract the editors for JOSS that are currently [hard-coded](https://github.com/openjournals/whedon-api/blob/e318e87d47c16c3bbd7808234c070f311d3a28db/whedon.rb#L11-L13).
- [x] Find a way to have different editors depending upon where the issue comment is coming from i.e. the [@nwo](https://github.com/openjournals/whedon-api/blob/e318e87d47c16c3bbd7808234c070f311d3a28db/whedon.rb#L34) param
- [x] Extract JOSS-specific language out of the Whedon [responses](https://github.com/openjournals/whedon-api/tree/master/responses) and other places [like this](https://github.com/openjournals/whedon-api/blob/e318e87d47c16c3bbd7808234c070f311d3a28db/whedon.rb#L112)

**Comment by parrish** [comment]
For the editors, we can just use this [API call](https://github.com/openjournals/whedon-api/blob/e318e87d47c16c3bbd7808234c070f311d3a28db/whedon.rb#L117) everywhere.  If we want to handle multiple nwo's, we can cache a nwo-keyed hash of editors.

> Extract JOSS-specific language

How about a non-secret YAML config for this?

**Comment by arfon** [comment]
@parrish - yes I think that's a good idea (basing the editor list from the GitHub team.

> How about a non-secret YAML config for this?

Sounds reasonable. We could also probably just make the language more generic (i.e. fits both journals).

**Comment by arfon** [comment]
@parrish I'm pretty sure this tracking issue can be closed out now right?

**Comment by parrish** [comment]
Yep! 🎉
